export const coupons = [
  {
    id: 1,
    title: "Hoichoi - Flat 46% OFF + Extra 12% OFF",
    description: "Get Flat 46% OFF on annual subscription plan + Extra 12% OFF using the promo code.",
    code: "GRABH",
    link: "https://www.grabon.in/hoichoi-coupons/",
    type: "code",
    brand: "Hoichoi",
    category: "Movies",
    expiryDate: "Ongoing",
    usageCount: "13.4k",
    isFeatured: true,
    rating: 4.8,
    totalReviews: 2340,
    discount: "46% + 12% OFF",
    badge: "HOT",
  },
  {
    id: 2,
    title: "Aha Gold: Flat 33% OFF + Additional Rs 260 OFF",
    description: "Subscribe to Aha Gold & grab flat 33% OFF for 12 months. Extra Rs 260 OFF with code.",
    code: "AHAGBGOLD",
    link: "https://www.grabon.in/aha-coupons/",
    type: "code",
    brand: "Aha",
    category: "Movies",
    expiryDate: "Ongoing",
    usageCount: "8.1k",
    isFeatured: true,
    rating: 4.6,
    totalReviews: 1890,
    discount: "33% OFF",
    originalPrice: "Rs 999",
    badge: "EXCLUSIVE",
  },
  {
    id: 3,
    title: "PVR INOX Monthly Passport: Just Rs 349",
    description: "Enjoy a new movie every week for 4 visits. Start your PVR INOX Monthly Passport now.",
    link: "https://www.grabon.in/pvr-cinemas-coupons/",
    type: "deal",
    brand: "PVR Cinemas",
    category: "Movies",
    expiryDate: "Ongoing",
    usageCount: "15.9k",
    isFeatured: true,
    rating: 4.9,
    totalReviews: 3210,
    discount: "Rs 349/mo",
    badge: "HOT",
  },
  {
    id: 4,
    title: "Netflix Mobile Subscription @ Rs 199",
    description: "Choose a mobile plan with offers starting at Rs 199. Watch it on two screens at the same time.",
    link: "https://www.grabon.in/netflix-coupons/",
    type: "deal",
    brand: "Netflix",
    category: "TV",
    expiryDate: "Ongoing",
    usageCount: "25k+",
    isFeatured: true,
    rating: 4.7,
    totalReviews: 5680,
    discount: "Rs 199/mo",
    badge: "EXCLUSIVE",
  },
  {
    id: 5,
    title: "Times Prime Power Pack: Flat Rs 950 OFF",
    description: "Enjoy access to OTT platforms like Zee5, Discovery+, Hungama & more. Gain exclusive benefits.",
    link: "https://www.grabon.in/times-prime-coupons/",
    type: "deal",
    brand: "Times Prime",
    category: "TV",
    expiryDate: "Limited",
    usageCount: "12.2k",
    isFeatured: false,
    rating: 4.8,
    totalReviews: 1120,
    discount: "Rs 950 OFF",
  },
  {
    id: 6,
    title: "Gaana Plus Subscription @ Rs 99",
    description: "Get 1 month subscription for Gaana with the best price. Download the app today.",
    link: "https://www.grabon.in/gaana-coupons/",
    type: "deal",
    brand: "Gaana",
    category: "Music",
    expiryDate: "Ongoing",
    usageCount: "5.2k",
    isFeatured: false,
    rating: 4.5,
    totalReviews: 876,
    discount: "Rs 99/mo",
    badge: "NEW",
  },
  {
    id: 7,
    title: "BookMyShow: Buy 1 Get 1 Free",
    description: "Buy 1 Get 1 Free on Movie Tickets when you use your IndusInd Bank Credit Cards.",
    link: "https://www.grabon.in/bookmyshow-coupons/",
    type: "deal",
    brand: "BookMyShow",
    category: "Movies",
    expiryDate: "Ongoing",
    usageCount: "4.3k",
    isFeatured: false,
    rating: 4.3,
    totalReviews: 654,
    discount: "BOGO",
  },
  {
    id: 8,
    title: "SonyLiv: 10% OFF on Annual Subscription",
    description: "Get Flat 10% OFF on your SonyLiv annual subscription plan for unlimited streaming.",
    link: "https://www.grabon.in/sonyliv-coupons/",
    type: "deal",
    brand: "SonyLiv",
    category: "TV",
    expiryDate: "Ongoing",
    usageCount: "6.7k",
    isFeatured: false,
    rating: 4.5,
    totalReviews: 1120,
    discount: "10% OFF",
  },
  {
    id: 9,
    title: "Playbox TV: Up To 65% OFF + Extra 10% OFF",
    description: "Subscribe to the annual plan & get up to 65% OFF. Also get an extra 10% OFF.",
    link: "https://www.grabon.in/playbox-tv-coupons/",
    type: "deal",
    brand: "Playbox TV",
    category: "TV",
    expiryDate: "Ongoing",
    usageCount: "3.4k",
    isFeatured: false,
    rating: 4.6,
    totalReviews: 780,
    discount: "65% OFF",
    badge: "NEW",
  },
  {
    id: 10,
    title: "ShemarooMe: Flat 15% OFF On Annual Plan",
    description: "Flat 15% OFF on the Annual package. Includes Classics & Blockbusters, New Web Series.",
    link: "https://www.grabon.in/shemaroome-coupons/",
    type: "deal",
    brand: "ShemarooMe",
    category: "Movies",
    expiryDate: "Ongoing",
    usageCount: "9k",
    isFeatured: false,
    rating: 4.8,
    totalReviews: 2100,
    discount: "15% OFF",
  },
  {
    id: 11,
    title: "ETV Win: Flat Rs 200 OFF + Extra Rs 100 OFF",
    description: "Flat Rs 200 OFF on annual plan + Extra Rs 100 OFF on Premium. Includes Health, Movies.",
    link: "https://www.grabon.in/etv-win-coupons/",
    type: "deal",
    brand: "ETV Win",
    category: "TV",
    expiryDate: "Ongoing",
    usageCount: "1.2k",
    isFeatured: true,
    rating: 4.9,
    totalReviews: 340,
    discount: "Rs 300 OFF",
    badge: "EXCLUSIVE",
  },
  {
    id: 12,
    title: "Comic Con: Indian Championship of Cosplay",
    description: "Participate by COSPLAYING & win amazing prizes. Book your pass now.",
    link: "https://www.grabon.in/comic-con-coupons/",
    type: "deal",
    brand: "Comic Con",
    category: "Events",
    expiryDate: "Ongoing",
    usageCount: "500+",
    isFeatured: false,
    rating: 4.2,
    totalReviews: 210,
    discount: "GIVEAWAYS",
  },
  {
    id: 13,
    title: "JioSaavn Pro: 1 Month Subscription @ Rs 99",
    description: "Get one month subscription plan @ Rs 99. Original shows, podcasts, and content.",
    link: "https://www.grabon.in/jiosaavn-coupons/",
    type: "deal",
    brand: "JioSaavn",
    category: "Music",
    expiryDate: "Ongoing",
    usageCount: "7.1k",
    isFeatured: false,
    rating: 4.4,
    totalReviews: 760,
    discount: "Rs 99/mo",
  },
  {
    id: 14,
    title: "Spotify Premium: 1 Month Free Trial",
    description: "Enjoy ad-free music listening, offline playback, and more. Cancel anytime.",
    link: "https://www.grabon.in/spotify-coupons/",
    type: "deal",
    brand: "Spotify",
    category: "Music",
    expiryDate: "Ongoing",
    usageCount: "19.5k",
    isFeatured: true,
    rating: 4.9,
    totalReviews: 4500,
    discount: "1 MONTH FREE",
    badge: "HOT",
  },
  {
    id: 15,
    title: "PlayStation Store: Up to 50% OFF on Games",
    description: "Massive savings on top-tier AAA game titles and indie gems alike.",
    link: "https://www.grabon.in/games-coupons/",
    type: "deal",
    brand: "PlayStation",
    category: "Gaming",
    expiryDate: "Limited",
    usageCount: "3.2k",
    isFeatured: true,
    rating: 4.8,
    totalReviews: 950,
    discount: "UP TO 50% OFF",
    badge: "HOT",
  },
  {
    id: 16,
    title: "Steam: 20% OFF Wallet Codes",
    description: "Top up your Steam wallet today and save 20% by using this exclusive code at checkout.",
    code: "STEAMWIN20",
    link: "https://www.grabon.in/games-coupons/",
    type: "code",
    brand: "Steam",
    category: "Gaming",
    expiryDate: "Ongoing",
    usageCount: "11.1k",
    isFeatured: false,
    rating: 4.7,
    totalReviews: 1200,
    discount: "20% OFF",
    badge: "EXCLUSIVE",
  },
  {
    id: 17,
    title: "Xbox Game Pass: First Month @ Rs 50",
    description: "Discover your next favorite game. Play hundreds of high-quality games with friends.",
    link: "https://www.grabon.in/games-coupons/",
    type: "deal",
    brand: "Xbox",
    category: "Gaming",
    expiryDate: "Ongoing",
    usageCount: "14.3k",
    isFeatured: true,
    rating: 4.9,
    totalReviews: 3100,
    discount: "Rs 50 TRIAL",
  },
  {
    id: 18,
    title: "WonderLa: Buy 3 Tickets, Get 1 Free",
    description: "Plan the ultimate family weekend. Grab the Buy 3 Get 1 offer on all WonderLa parks.",
    link: "https://www.grabon.in/amusement-water-park-coupons/",
    type: "deal",
    brand: "WonderLa",
    category: "Amusement",
    expiryDate: "Ongoing",
    usageCount: "6.5k",
    isFeatured: false,
    rating: 4.6,
    totalReviews: 890,
    discount: "BUY 3 GET 1",
  },
  {
    id: 19,
    title: "Sunburn Arena: 10% OFF Early Bird Phase 2",
    description: "Get early access and 10% off on all VVIP and Gen-Z zones at Sunburn Festival.",
    code: "SUNBURN10",
    link: "https://www.grabon.in/events-coupons/",
    type: "code",
    brand: "Sunburn",
    category: "Events",
    expiryDate: "Limited",
    usageCount: "8.8k",
    isFeatured: true,
    rating: 4.9,
    totalReviews: 2400,
    discount: "10% OFF",
    badge: "HOT",
  },
  {
    id: 20,
    title: "Art Biennale: Flat 25% OFF on Exhibitions",
    description: "Dive into contemporary culture. Use code to slash 25% off all gallery hopping passes.",
    code: "ART25",
    link: "https://www.grabon.in/events-coupons/",
    type: "code",
    brand: "Gallery",
    category: "Exhibitions",
    expiryDate: "Ongoing",
    usageCount: "1.2k",
    isFeatured: false,
    rating: 4.5,
    totalReviews: 310,
    discount: "25% OFF",
  },
  {
    id: 21,
    title: "MakeMyTrip: 20% OFF Domestic Flights",
    description: "Book your next domestic flight and get an instant 20% OFF up to Rs 1500 using this code.",
    code: "MMTSAVE20",
    link: "https://www.makemytrip.com/",
    type: "code",
    brand: "MakeMyTrip",
    category: "Travel",
    expiryDate: "Limited",
    usageCount: "12.5k",
    isFeatured: true,
    rating: 4.8,
    totalReviews: 3100,
    discount: "20% OFF"
  },
  {
    id: 22,
    title: "Agoda: Flat 15% OFF Global Hotels",
    description: "Plan your international vacation. Save a flat 15% on hotel bookings worldwide.",
    link: "https://www.agoda.com/",
    type: "deal",
    brand: "Agoda",
    category: "Travel",
    expiryDate: "Ongoing",
    usageCount: "9.2k",
    isFeatured: false,
    rating: 4.5,
    totalReviews: 1200,
    discount: "15% OFF"
  },
  {
    id: 23,
    title: "KidZania: Rs 500 OFF Family Pass",
    description: "A fun and educational experience for kids! Get Rs 500 OFF when booking a Family Pass of 4.",
    code: "KZ500",
    link: "https://india.kidzania.com/",
    type: "code",
    brand: "KidZania",
    category: "Family",
    expiryDate: "Ongoing",
    usageCount: "5.1k",
    isFeatured: true,
    rating: 4.9,
    totalReviews: 890,
    discount: "Rs 500 OFF",
    badge: "EXCLUSIVE"
  },
  {
    id: 24,
    title: "Hamleys: Flat 10% OFF Toys",
    description: "Surprise your little ones with the finest toys. Flat 10% OFF on online orders above Rs 2000.",
    link: "https://www.hamleys.in/",
    type: "deal",
    brand: "Hamleys",
    category: "Family",
    expiryDate: "Ongoing",
    usageCount: "6.8k",
    isFeatured: false,
    rating: 4.6,
    totalReviews: 950,
    discount: "10% OFF"
  },
  {
    id: 25,
    title: "Imagicaa: 15% OFF Theme Park Tickets",
    description: "Experience India's largest theme park! Flat 15% OFF on standard and express tickets.",
    code: "FUN15",
    link: "https://www.imagicaaworld.com/",
    type: "code",
    brand: "Imagicaa",
    category: "Amusement",
    expiryDate: "Limited",
    usageCount: "8.7k",
    isFeatured: true,
    rating: 4.7,
    totalReviews: 2400,
    discount: "15% OFF",
    badge: "HOT"
  },
  {
    id: 26,
    title: "Auto Expo 2026: 10% OFF Entry Passes",
    description: "Witness the future of mobility. Get 10% OFF your early-bird tickets now.",
    link: "https://www.autoexpo.in/",
    type: "deal",
    brand: "Auto Expo",
    category: "Exhibitions",
    expiryDate: "Limited",
    usageCount: "3.4k",
    isFeatured: false,
    rating: 4.8,
    totalReviews: 450,
    discount: "10% OFF"
  },
  {
    id: 27,
    title: "Disney+ Hotstar: Super Plan @ Rs 899/yr",
    description: "Catch edge-of-the-seat live sports and exclusive movies. Opt for the Super Plan today.",
    link: "https://www.hotstar.com/",
    type: "deal",
    brand: "Disney+ Hotstar",
    category: "TV",
    expiryDate: "Ongoing",
    usageCount: "30k+",
    isFeatured: true,
    rating: 4.8,
    totalReviews: 8900,
    discount: "Rs 899/yr",
    badge: "HOT"
  },
  {
    id: 28,
    title: "Cult.fit: Flat 20% OFF Pro Membership",
    description: "Get healthy, get fit. Grab a 20% discount on 6 and 12-month Cult Pass Pro memberships.",
    code: "CULTPRO20",
    link: "https://www.cult.fit/",
    type: "code",
    brand: "Cult.fit",
    category: "Fitness",
    expiryDate: "Ongoing",
    usageCount: "14k",
    isFeatured: true,
    rating: 4.9,
    totalReviews: 4500,
    discount: "20% OFF",
    badge: "EXCLUSIVE"
  },
  {
    id: 29,
    title: "HealthifyMe: Rs 1000 OFF on Diet Plans",
    description: "Your personal AI and human coach combined. Save big on the premium transformation plan.",
    link: "https://www.healthifyme.com/",
    type: "deal",
    brand: "HealthifyMe",
    category: "Fitness",
    expiryDate: "Ongoing",
    usageCount: "8.3k",
    isFeatured: false,
    rating: 4.7,
    totalReviews: 3200,
    discount: "Rs 1000 OFF"
  },
  {
    id: 30,
    title: "ESL Pro Tour: 10% OFF Weekend VIP Passes",
    description: "Experience e-sports history live. Get VIP weekend passes with a 10% discount.",
    code: "ESLVIP",
    link: "https://pro.eslgaming.com/",
    type: "code",
    brand: "ESL",
    category: "E-Sports",
    expiryDate: "Limited",
    usageCount: "4.4k",
    isFeatured: true,
    rating: 4.9,
    totalReviews: 500,
    discount: "10% OFF"
  },
  {
    id: 31,
    title: "Twitch: 20% OFF Gift Subscriptions",
    description: "Support your favorite streamers. Bulk purchase 5+ gift subs and get 20% OFF.",
    link: "https://www.twitch.tv/",
    type: "deal",
    brand: "Twitch",
    category: "E-Sports",
    expiryDate: "Ongoing",
    usageCount: "15k+",
    isFeatured: false,
    rating: 4.8,
    totalReviews: 2100,
    discount: "20% OFF"
  }
];
